### ISSUE TITLE
Paladin and Archer improvement

### ISSUE THREAD

**Issue by tnevolin** [tnevolin/mm6-skill-emphasis-mod#3]
# Thoughts

- Give them ability to master all magic skills all at once. That will make their magic strength grow faster in all realms.
- Increase certain spells power/effect for these classes.

**Comment by RawSugr** [comment]
Issues for the classes are;
1. relatively little return pr point when investing in spells because of low mana; they get ½ as much out of ranking as mages, and with the mod the same is true of weapon skill compared to knights
2. The worst hp/mp off all classes
3. their supposed benefit is access to many skills but to benefit they need to spread out their skillpoints, and their abilities rarely stack; they can either use weapon OR spell, not both.

fixes:
1. Added benefit to bow and melee for paladin is a good start. But they need something similar for spells. I like the suggestion of simultanous ranking magic schools (its mine), alternative could be spells that boost their melee/ranged damage (could be available to all classes but would be more relevant for these) would require spells that are only castable on the caster.
2. I'd suggest paladin +1 hp pr level and archer +1 MP
3. An easy (?) fix would be to increase their skillpoints, if they got +50% skillpoints that would balance with their reduced benefit pr skillpoint.

So you can add more skillpoints pr level as a fix, and spells that boost weapondamage for the caster as example of "Increase certain spells power/effect for these classes."

regardless of the adopted fix they need the boost to HP/MP imo

**Comment by tnevolin** [comment]
Agree on analysis.

- Simultaneous advancement in multiple magic schools seems right. Worth trying.
- Adding HP/SP does not seem right as then they will be just close to knight/caster classes. What the point of having different classes. Besides, after last promotion Warrior Mage has 3 SP/level versus casters 5 SP/level - not too big a difference.
- I would also suggest for archer to increase effect of all magic projectile spells. For paladin - healing/spirit spells?

My general idea is to strengthen them by making them more dissimilar from other classes, not more similar.

**Comment by RawSugr** [comment]
Bonus to magic is a simple, effective fix. Say increasing their casting rank by 50%. (reasonable because they have half mana which is near analogous to double cost)
Simultaneous advancement in multiple magic schools is also a hefty bonus though, so if they are given both i'd go with +20%. It could be every spell far as im concerned, certainly for palas, maybe just projectiles for archers.

For the hp/mp; they are also hit by a worse bonus mana from stats, so in my experience its half vs casters rather than 3:5, that could be fixed as well -  and maybe palas could benefit from bodybuilding as if they were knights. Covering while wearing plate is a lot for a semisquishy pala.

**Comment by tnevolin** [comment]
Ah, you are talking about 50% spell power/effect increase. Yes. That is what I meant by increasing their effect on certain spells. My version for archer is to double their projectile spells damage.

RE: paladin body building. I think everybody gets the same exactly body building bonus. It is purely additive. Paladin will have less HP than knight throughout the game but there is not much room for improvement. They just 3:4 comparing to knight at the beginning. We cannot go fractional in this game. We can reduce covering effect for paladin to not overuse their HP. For example, when knight absorbs 10% of hits paladin can do 5% or something of the sort. Giving him some super improved certain spell power should be distinguishable enough. What do you think?

**Comment by RawSugr** [comment]
bodybuilding gives better bonuses for knights , but looking it up its based on base class so not really possible :) nvm, i still say archer/pala has worse hp/MP but we're talking about considerable bonuses so i guess its fine, its not a lot.

+100% seems fine since projectiles overlap with the archer bow skill in role, but then I wouldnt give him simultanous ranking, maybe 50% and simultanous? 

Ideal would be for palas to cover 5% - and to double that when using shield and get extra bonuses to damage and defense pr rank when using shields giving the option of a tanky and a 2H wieldng damage dealing paladin - but just 5% would be fine i think. 
I personally wouldnt make palas spellpower specific but rather 20% to everything and simultanous - but its your mod :) clerical spells do four things; heal, cure debuffs, buff party and deal damage. I guess if i had to choose i'd increase effect of bless and heroism, again this could be 100%, or 50% + simultanous but i prefer 20% to everything - or just 0%, palas get much more value for their spells since healing etc dont overlap with damage dealing the way spells do for archers.

**Comment by RawSugr** [comment]
also be aware that archers getting +100% to projectiles you risk making archers use bows only as a secondary weapon. I could see making a party of archers casting hyper powerful projectiles with bow and weapon at a much lower rank to clean up anything that survives. Thats not a balance issue as such though, but you might find it problematic on other grounds :)

**Comment by tnevolin** [comment]
Noted. Then maybe we should leave them to bows and increase bow damage with skill slightly.

**Comment by RawSugr** [comment]
yeah maybe, like i said i'd really love to see bows appear on those charts you have of weapon damage, for archers and others. I think archers should around 1/3rd* the damage of knights, ending with ~333 at 1000 skillpoints, and knights should do around half that. It seems like that adding +1 damage at expert would achieve something like that but im not sure? maybe making + damage an archer skill is closer to that outcome? And they could still get a boost on top of that, whether 25-50 to projecticles or simultanous.

**Comment by RawSugr** [comment]
or actually looking at the charts what might achieve it is for master to grant +1 damage and archers to have the double arrow ability innate....but i dont know if you can remove duo arrow from the bow skill?

Or maybe the damage is already around that level for knighta and the archer ability should be + damage? i just cant tell:)

**Comment by tnevolin** [comment]
Duo arrow - probably cannot remove. It is hardcoded somewhere in the engine.
Other numeric adjustments - sure.

**Comment by RawSugr** [comment]
i think whats needed is just replace the archer benefit with +1 damage instead of recovery but im not 100% on the math/mechanics. should be simple for you to plot in your formulas. target is archers using bow dealing 1/3 knight melee damage and half that for knights.
Stray thought; a bonus for paladins could be access to dark/light. that would allow for pure plate armor/melee parties, although palas will struggle to cast all those expensive buffs.If not an option or you dont like the idea my suggestion would be just simultanous clerical.

**Comment by RawSugr** [comment]
regarding monster damage:
you think this would work:
		-- multiply monster damage

		local monsterLevel = Game.MonstersTxt[monsterTxtIndex].Level		
		monsterTxt.Attack1.DamageDiceCount = math.round(monsterTxt.Attack1.DamageDiceCount * (monsterLevel/20 +1))
		monsterTxt.Attack1.DamageAdd = math.round(monsterTxt.Attack1.DamageAdd *  (monsterLevel/20 +1))

i'd rather multiply the max roll than # of dice, is that an option?

**Comment by RawSugr** [comment]
Using this now and found the numbers for spell :)

-- multiply monster damage
local monsterLevel = Game.MonstersTxt[monsterTxtIndex].Level
monsterTxt.Attack1.DamageDiceSides = math.round(monsterTxt.Attack1.DamageDiceSides * ((monsterLevel+5)/20 +1))
monsterTxt.Attack1.DamageAdd = math.round(monsterTxt.Attack1.DamageAdd * ((monsterLevel+5)/20 +1))

monsterTxt.Attack2.DamageDiceCount = monsterTxt.Attack2.DamageDiceCount * monsterDamageMultiplier / monsterDamageMultiplier
monsterTxt.Attack2.DamageAdd = monsterTxt.Attack2.DamageAdd * monsterDamageMultiplier / monsterDamageMultiplier

[i dont know if local Mlvl is neccesary, and yes you can also remove the line for attack2 entirely.]

**Comment by RawSugr** [comment]
hmm odd im trying to change the values in the spells you linked but nothing happens when i load game?

**Comment by tnevolin** [comment]
> regarding monster damage:
> i'd rather multiply the max roll than # of dice, is that an option?

Yes. That should work. I used dice count because my multiplier was a whole number. You can modify min/max damage as well. Check [MMExtensions](https://grayface.github.io/mm/ext/ref/) structs.MonsterAttackInfo DamageDiceSides. This essentially increases the max roll. However, you need to round them to whole number still.

**Comment by tnevolin** [comment]
> hmm odd im trying to change the values in the spells you linked but nothing happens when i load game?

Some of them are commented out by me. Remnant of previous edits those I cancelled.
[spell powers](https://github.com/tnevolin/mm6-skill-emphasis-mod/blob/55d490d13cb81d9a0b13270a9a1c5b3315d850a0/Scripts/General/skill-mod.lua#L355)
```
	--[[
	-- Fire Bolt
	[4] =
	{
		[const.Novice] = {fixedMin = 7, fixedMax = 7, variableMin = 1, variableMax = 7, },
		[const.Expert] = {fixedMin = 7, fixedMax = 7, variableMin = 1, variableMax = 7, },
		[const.Master] = {fixedMin = 7, fixedMax = 7, variableMin = 1, variableMax = 7, },
	},
	--]]
```

First and last line are block comment markers. Remove them if you want you edits to be active.

**Comment by tnevolin** [comment]
Besides, I recommend you to insert this line at the very top first to make sure this is an exact script that is used by game.

```
MessageBox("my script")
```

It should show you system dialog with this text at the very beginning of the game. This way you know you are editing right script.
This message is actually a powerful debug tool. You can output any variables at any moment.

**Comment by tnevolin** [comment]
> i think whats needed is just replace the archer benefit with +1 damage instead of recovery but im not 100% on the math/mechanics. should be simple for you to plot in your formulas. target is archers using bow dealing 1/3 knight melee damage and half that for knights. Stray thought; a bonus for paladins could be access to dark/light. that would allow for pure plate armor/melee parties, although palas will struggle to cast all those expensive buffs.If not an option or you dont like the idea my suggestion would be just simultanous clerical.

Damage is more powerful than recovery. Estimate knight damage and get 1/3 of this and give this to bow/archer.

Paladin access to mirror magic - I think this is doable. There should be a table governing magic usage.

**Comment by RawSugr** [comment]
I was thinking one way to achieve the desired balance for bow would be to reduce (halve+) recovery for rank for all and give everyone +1 damage - archer ability could then be to double damage and/or recovery, whatever is needed to double.
Ill see about getting more acquinted with your spreadsheet to see if i can plot in the values. There arent a lot of headlines ;)

Thanks a bunch for explaining the block comment markers - were driving me insane^^

**Comment by tnevolin** [comment]
You are most welcome.
😁

Sorry, about not too clear headers in spreadsheet. Was creating it for myself only. Feel free to convert it something more beautiful that everyone can use/share!

**Comment by RawSugr** [comment]
is it easy to give the simultanous leveling to A/P, can you show me how? seems easy enough to give it to everyone but thats not what i want :)

**Comment by Malekitsu** [comment]
fixes under testing

**Comment by Malekitsu** [comment]
with the new changes paladin seems very strong and a solid alternative to knight/cleric!
Archers unless we change design can't work with bugged bow damage.

**Comment by tnevolin** [comment]
Good. I'll assign it to you then to take over.

**Comment by Malekitsu** [comment]
I'm giving archers bonus meele damage when promoting into battle mage and warrior mage, as a substitute for bow.
Can close the issue for now.
